### ISSUE TITLE
Validator missing SPARK_ON_YARN service type

### ISSUE THREAD

**Issue by dereklwood** [cloudera/cm_ext#14]
After adding a dependency on the ``SPARK_ON_YARN`` service type to our custom CSD, it no longer passes the validator.  However it works fine in CM (confirmed on 5.5, 5.7).  It seems the validator is missing this valid service type

```
Validating: src/descriptor/service.sdl
==> SPARK_ON_YARN must be a valid service type
```

**Comment by markgrover** [comment]
Thanks, Derek. That's an issue I have run into as well - the validator seems to only think of 1st party services (e.g. HDFS, YARN, HIVE, etc.) to be the only valid ones. I think it allows for additional valid service names to be provided by command line, but they aren't being used as far as I can tell.

**Comment by dereklwood** [comment]
Ah thanks, I didn't realize you could pass in additional service types.  The following does appear to work for me:

```
$ java -jar validator.jar -s src/descriptor/service.sdl -l SPARK_ON_YARN
Validating: src/descriptor/service.sdl
Validation succeeded.
```

So I'll go ahead and close this.  It would be nice to include these common components by default but i'm guessing they are keeping it compatible with CM4.

**Comment by blindenvy** [comment]
I am experiencing this same issue when trying to use the schema-validator-maven-plugin. I have the plugin configured as follows:

```
      <plugin>
        <groupId>com.cloudera.enterprise</groupId>
        <artifactId>schema-validator-maven-plugin</artifactId>
        <version>5.8.0</version>
        <executions>
          <execution>
            <id>validate-schema</id>
            <phase>test</phase>
            <goals>
              <goal>validate</goal>
            </goals>
            <configuration>
              <sourceDirectory>src</sourceDirectory>
              <strictMode>true</strictMode>
            </configuration>
          </execution>
        </executions>
      </plugin>
```

And I receive the following error:
```
[INFO] --- schema-validator-maven-plugin:5.8.0:validate (validate-schema) @ foo-cloudera-csd ---
[ERROR] Validating: /some/path/code/foo/foo-cloudera-csd/src/main/resources/descriptor/service.sdl
==> SPARK_ON_YARN must be a valid service type
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 2.149 s
[INFO] Finished at: 2016-07-28T14:32:47-04:00
[INFO] Final Memory: 18M/303M
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal com.cloudera.enterprise:schema-validator-maven-plugin:5.8.0:validate (validate-schema) on project foo-cloudera-csd: Encountered 1 errors -> [Help 1]
[ERROR]
```

I used the mvn help function to describe the configuration available for the plugin but it doesn't seem there are any options to list additional service types. Is there a way to do this that I simply missed or is this something that can be added?

**Comment by mcapitanio** [comment]
@blindenvy You have to specify:

    <configuration>
        <addValidServiceTypes>SPARK_ON_YARN</addValidServiceTypes>
    </configuration>

**Comment by chufucun** [comment]
This configuration works:
```xml
     <plugin>
        <groupId>com.cloudera.enterprise</groupId>
        <artifactId>schema-validator-maven-plugin</artifactId>
        <version>6.3.0</version>
        <executions>
          <execution>
            <id>validate-schema</id>
          </execution>
        </executions>
        <!-- The list containing additional valid service types separated by space. For example, "FOO BAR" -->
        <configuration>
          <addValidServiceTypes>SPARK_ON_YARN</addValidServiceTypes>
        </configuration>
      </plugin>

```
