### ISSUE TITLE
Maven build error

### ISSUE THREAD

**Issue by texasmichelle** [cloudera/cm_ext#8]
This looks like it's related to https://github.com/cloudera/cm_ext/issues/4. When I run `mvn install` in the validator directory from a fresh checkout, I see this error: 
`[ERROR] Failed to execute goal on project schema-validator: Could not resolve dependencies for project com.cloudera.enterprise:schema-validator:jar:5.4.0: Could not find artifact com.cloudera.cmf.schema:cloudera-manager-schema:jar:5.4.0 in cloudera-external (https://repository.cloudera.com/artifactory/ext-release-local/) -> [Help 1]`

I can see 	`schema-validator-5.4.0.jar` in `libs-staging-local`, but nothing in `ext-release-local`.

**Comment by philipl** [comment]
You should mvn install at the top level. The cm-schema sub-project will install this artefact for you - so you'd normally not pull it from artifactory at all.

**Comment by texasmichelle** [comment]
Right you are. I should have looked at the readme at the top level, not the validator directory. Thanks for the quick reply!
